# Generated by Django 5.0.4 on 2024-04-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pbl5',
            fields=[
              
            ],
        ),
    ]
